apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ft-services.info
    http:
      paths:
        - path: /
          backend:
            serviceName: nginx
            servicePort: 80
