kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    # - name: ssh
    #   port: 22
    #   nodePort: 22
    - name: http
      port: 80
      nodePort: 80
    - name: https
      port: 443
      nodePort: 443
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx_alpine
        imagePullPolicy: Never
        name: nginx
        env:
        - name: SSH_USER
          value: admin
        - name: SSH_PASSWORD
          value: admin
        ports:
        # - containerPort: 22
        #   name: ssh
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
